# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Document-Manager
version:      0.30
version_from: lib/Document/Manager.pm
installdirs:  site
requires:
    Carp:                          1
    Config::Simple:                0
    File::Copy:                    2
    File::Find:                    1
    File::Path:                    1
    File::Spec:                    0
    Getopt::Long:                  2
    Pod::Usage:                    1
    RDF::Simple:                   0
    WebService::TicketAuth:        0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.20
