# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Document-Manager
version:      0.25
version_from: lib/Document/Manager.pm
installdirs:  site
requires:
    Carp:                          1.01
    File::Copy:                    2.05
    File::Find:                    1.04
    File::Path:                    1.05
    File::Spec:                    0.83
    Getopt::Long:                  2.32
    Pod::Usage:                    1.14

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.20
